language: python
python:
  - "3.8.2"
  
branches:
  only:
    - master

install:
- pip install mkdocs
- pip install mkdocs-material
- pip install mkdocs-minify-plugin

script:
  - git clean -f -d -x
  - mkdocs build --clean
  - rm -rf ./docs;mv site/* .

deploy:
  provider: pages
  # 保留构建后的文件
  skip_cleanup: true
  target_branch: gh-pages
  token: $GITHUB_TOKEN
  # 每次部署会新增一个提交记录再推送，而不是使用 git push --force。
  keep_history: true
  on:
    branch: master
